# Generated by Django 3.2.6 on 2021-08-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.source')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionset')),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quote')),
                ('source_1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_1', to='quiz.source')),
                ('source_2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_2', to='quiz.source')),
                ('source_3_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_3', to='quiz.source')),
                ('source_4_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_4', to='quiz.source')),
            ],
        ),
    ]
