# Generated by Django 3.2.6 on 2021-08-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
